/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Critical.c
**     Project     : ProcessorExpert
**     Processor   : MK21DX256VLK5
**     Component   : CriticalSection
**     Version     : Component 01.006, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-06-18, 16:58, # CodeGen: 73
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         CriticalVariable - void Critical_CriticalVariable(void);
**         EnterCritical    - void Critical_EnterCritical(void);
**         ExitCritical     - void Critical_ExitCritical(void);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2014, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file Critical.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup Critical_module Critical module documentation
**  @{
*/         

/* MODULE Critical. */

#include "Critical.h"

/*
** ===================================================================
**     Method      :  Critical_CriticalVariable (component CriticalSection)
**     Description :
**         Defines a variable if necessary. This is a macro.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Critical_CriticalVariable(void)
{
  *** Implemented as macro in the header file Critical.h
}
*/

/*
** ===================================================================
**     Method      :  Critical_EnterCritical (component CriticalSection)
**     Description :
**         Enters a critical section
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Critical_EnterCritical(void)
{
  *** Implemented as macro in the header file Critical.h
}
*/

/*
** ===================================================================
**     Method      :  Critical_ExitCritical (component CriticalSection)
**     Description :
**         Exits a critical section
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Critical_ExitCritical(void)
{
  *** Implemented as macro in the header file Critical.h
}
*/

/* END Critical. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
