/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Critical.h
**     Project     : ProcessorExpert
**     Processor   : MK21DX256VLK5
**     Component   : CriticalSection
**     Version     : Component 01.006, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-06-20, 01:12, # CodeGen: 71
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         CriticalVariable - void Critical_CriticalVariable(void);
**         EnterCritical    - void Critical_EnterCritical(void);
**         ExitCritical     - void Critical_ExitCritical(void);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2014, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file Critical.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup Critical_module Critical module documentation
**  @{
*/         

#ifndef __Critical_H
#define __Critical_H

/* MODULE Critical. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "Cpu.h"


/* workaround macros for wrong EnterCritical()/ExitCritical() in the low level drivers. Will be removed once PEx is fixed */
#define Critical_CriticalVariableDrv() \
  Critical_CriticalVariable()
#define Critical_EnterCriticalDrv() \
  Critical_EnterCritical()
#define Critical_ExitCriticalDrv() \
  Critical_ExitCritical()

#define Critical_CriticalVariable() \
  uint8_t cpuSR; /* variable to store current status */

/*
** ===================================================================
**     Method      :  Critical_CriticalVariable (component CriticalSection)
**     Description :
**         Defines a variable if necessary. This is a macro.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Critical_EnterCritical(saveState) \
  do {                                  \
    __asm (                             \
    "MRS   R0, PRIMASK\n\t"             \
    "CPSID I\n\t"                       \
    "STRB R0, %[output]"                \
    : [output] "=m" (saveState) :: "r0");   \
  } while(0)

/*
** ===================================================================
**     Method      :  Critical_EnterCritical (component CriticalSection)
**     Description :
**         Enters a critical section
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Critical_ExitCritical(restoreState) \
  do{                                  \
    __asm (                            \
    "ldrb r0, %[input]\n\t"            \
    "msr PRIMASK,r0;\n\t"              \
    ::[input] "m" (restoreState) : "r0");     \
  } while(0)

/*
** ===================================================================
**     Method      :  Critical_ExitCritical (component CriticalSection)
**     Description :
**         Exits a critical section
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END Critical. */

#endif
/* ifndef __Critical_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
