/*
 * gatewayCommonTypes.h
 *
 *  Created on: Mar 1, 2016
 *      Author: andrewhuff
 */

#ifndef APPLICATION_CONFIGURE_GATEWAYCOMMONTYPES_H_
#define APPLICATION_CONFIGURE_GATEWAYCOMMONTYPES_H_


// --------------------------------------------------------------------------
// Definitions.

#define UNIQUE_ID_BYTES			8
#define ASSOC_RST_DATA_LEN		2

#define PROTOCOL_VER_0			0x00
#define PROTOCOL_VER_1			0x01

#define V0_BROADCAST_NET_NUM		0x0f
#define V0_ADDR_CONTROLLER			0x00
#define V0_ADDR_BROADCAST			0xff

#define V1_ADDR_CONTROLLER			0x0000
#define V1_ADDR_BROADCAST			0xffff
#define V1_BROADCAST_NET_NUM		0x0f


#define PRIVATE_GUID			"00000000"

/*
 * The format of PROTOCOL_VER_0 on the network is as follows:
 *
 * 2b - Version
 * 1b - Ack requested bit
 * 1b - Reserved
 * 4b - Network number
 * 1B - Packet source address
 * 1B - Packet dest address
 * 1B - Ack Id
 *
 * ========== End of Logical Header =========
 *
 * 4b - Command ID
 * 4b - Command endpoint
 * nB - Command bytes
 *
 * Where B = byte, b = bit
 *
 */

/*
 * The format of a PROTOCOL_VER_1 on the network is as follows:
 *
 * 2b - Version
 * 1b - Ack requested bit
 * 1b - Reserved
 * 4b - Network number
 * 2B - Packet source address
 * 2B - Packet dest address
 * 1B - Ack Id
 * 2B - Packet Payload CRC
 *
 * ========== End of Logical Header =========
 *
 * 4b - Command ID
 * 4b - Command endpoint
 * nB - Command bytes
 *
 * Where B = byte, b = bit
 *
 */

// Command format positioning constant PROTOCOL_VER_1
// Packet

#define V0_PCKPOS_VERSION			0
#define V0_PCKPOS_PCK_TYPE_BIT		V0_PCKPOS_VERSION
#define V0_PCKPOS_RESERVED			V0_PCKPOS_PCK_TYPE_BIT
#define V0_PCKPOS_NET_NUM			V0_PCKPOS_RESERVED
#define V0_PCKPOS_SRC_ADDR			V0_PCKPOS_NET_NUM + 1
#define V0_PCKPOS_DST_ADDR 			V0_PCKPOS_SRC_ADDR + 1
#define V0_PCKPOS_ACK_ID			V0_PCKPOS_DST_ADDR + 1
#define V0_PCKPOS_HDR_ENDPOINT		V0_PCKPOS_ACK_ID + 1

#define V0_CMDPOS_CMD_ID			V0_PCKPOS_HDR_ENDPOINT
#define V0_CMDPOS_ENDPOINT			V0_CMDPOS_CMD_ID

#define V0_CMDPOS_STARTOFCMD		V0_CMDPOS_ENDPOINT + 1
#define V0_PCKPOS_ACK_DATA			V0_CMDPOS_ENDPOINT + 1

// Network Mgmt
#define V0_CMDPOS_NETM_SUBCMD			V0_CMDPOS_STARTOFCMD
#define V0_CMDPOS_NETM_CHKCMD_TYPE		V0_CMDPOS_NETM_SUBCMD + 1
#define V0_CMDPOS_NETM_CHKCMD_NET_NUM	V0_CMDPOS_NETM_CHKCMD_TYPE + 1
#define V0_CMDPOS_NETM_CHKCMD_GUID		V0_CMDPOS_NETM_CHKCMD_NET_NUM + 1
#define V0_CMDPOS_NETM_CHKCMD_CHANNEL	V0_CMDPOS_NETM_CHKCMD_GUID + 8
#define V0_CMDPOS_NETM_CHKCMD_ENERGY	V0_CMDPOS_NETM_CHKCMD_CHANNEL + 1
#define V0_CMDPOS_NETM_CHKCMD_LINKQ		V0_CMDPOS_NETM_CHKCMD_ENERGY + 1
#define V0_CMDPOS_NETM_TSTCMD_NUM		V0_CMDPOS_NETM_SUBCMD + 1
#define V0_CMDPOS_NETM_ACKCMD_ID		V0_CMDPOS_NETM_SUBCMD + 1
#define V0_CMDPOS_NETM_SETCMD_CHANNEL	V0_CMDPOS_NETM_SUBCMD + 1

// Assoc Command
#define V0_CMDPOS_ASSOC_SUBCMD		V0_CMDPOS_STARTOFCMD
#define V0_CMDPOS_ASSOC_GUID		V0_CMDPOS_ASSOC_SUBCMD + 1

#define V0_CMDPOS_ASSOCREQ_HW_VER	V0_CMDPOS_ASSOC_GUID + 8
#define V0_CMDPOS_ASSOCREQ_FW_VER	V0_CMDPOS_ASSOCREQ_HW_VER + 4
#define V0_CMDPOS_ASSOCREQ_RP_VER	V0_CMDPOS_ASSOCREQ_FW_VER + 4
#define V0_CMDPOS_ASSOCREQ_SYSSTAT 	V0_CMDPOS_ASSOCREQ_RP_VER + 1

#define V0_CMDPOS_ASSOCRESP_ADDR	V0_CMDPOS_ASSOC_GUID + 8
#define V0_CMDPOS_ASSOCRESP_NET		V0_CMDPOS_ASSOCRESP_ADDR + 2
#define V0_CMDPOS_ASSOCRESP_SLEEP	V0_CMDPOS_ASSOCRESP_NET + 1
#define V0_CMDPOS_ASSOCRESP_SCANNER V0_CMDPOS_ASSOCRESP_SLEEP + 2

#define V0_CMDPOS_ASSOCACK_STATE	V0_CMDPOS_ASSOC_GUID + 8
#define V0_CMDPOS_ASSOCACK_TIME		V0_CMDPOS_ASSOCACK_STATE + 1

#define V0_CMDPOS_ASSOCCHK_BATT		V0_CMDPOS_ASSOC_GUID + 8
#define V0_CMDPOS_ASSOCCHK_LRC		V0_CMDPOS_ASSOCCHK_BATT + 1
#define V0_CMDPOS_ASSOCCHK_RCM0		V0_CMDPOS_ASSOCCHK_LRC + 1
#define V0_CMDPOS_ASSOCCHK_RCM1		V0_CMDPOS_ASSOCCHK_RCM0 + 1
#define V0_CMDPOS_ASSOCCHK_PC		V0_CMDPOS_ASSOCCHK_RCM1 + 1

// Command format positioning constant PROTOCOL_VER_1
// Packet
#define V1_PCKPOS_VERSION			0
#define V1_PCKPOS_PCK_TYPE_BIT		V1_PCKPOS_VERSION
#define V1_PCKPOS_RESERVED			V1_PCKPOS_PCK_TYPE_BIT
#define V1_PCKPOS_NET_NUM			V1_PCKPOS_RESERVED
#define V1_PCKPOS_SRC_ADDR			V1_PCKPOS_NET_NUM + 1
#define V1_PCKPOS_DST_ADDR 			V1_PCKPOS_SRC_ADDR + 2
#define V1_PCKPOS_ACK_ID			V1_PCKPOS_DST_ADDR + 2
#define V1_PCKPOS_CRC				V1_PCKPOS_ACK_ID + 1
#define V1_PCKPOS_HDR_ENDPOINT		V1_PCKPOS_CRC + 2

#define V1_CMDPOS_CMD_ID			V1_PCKPOS_HDR_ENDPOINT
#define V1_CMDPOS_ENDPOINT			V1_CMDPOS_CMD_ID

#define V1_CMDPOS_STARTOFCMD		V1_CMDPOS_ENDPOINT + 1
#define V1_PCKPOS_ACK_DATA			V1_CMDPOS_ENDPOINT + 1

// Network Mgmt
#define V1_CMDPOS_NETM_SUBCMD			V1_CMDPOS_STARTOFCMD
#define V1_CMDPOS_NETM_CHKCMD_TYPE		V1_CMDPOS_NETM_SUBCMD + 1
#define V1_CMDPOS_NETM_CHKCMD_NET_NUM	V1_CMDPOS_NETM_CHKCMD_TYPE + 1
#define V1_CMDPOS_NETM_CHKCMD_GUID		V1_CMDPOS_NETM_CHKCMD_NET_NUM + 1
#define V1_CMDPOS_NETM_CHKCMD_CHANNEL	V1_CMDPOS_NETM_CHKCMD_GUID + 8
#define V1_CMDPOS_NETM_CHKCMD_ENERGY	V1_CMDPOS_NETM_CHKCMD_CHANNEL + 1
#define V1_CMDPOS_NETM_CHKCMD_LINKQ		V1_CMDPOS_NETM_CHKCMD_ENERGY + 1
#define V1_CMDPOS_NETM_TSTCMD_NUM		V1_CMDPOS_NETM_SUBCMD + 1
#define V1_CMDPOS_NETM_ACKCMD_ID		V1_CMDPOS_NETM_SUBCMD + 1
#define V1_CMDPOS_NETM_SETCMD_CHANNEL	V1_CMDPOS_NETM_SUBCMD + 1

// Assoc Command
#define V1_CMDPOS_ASSOC_SUBCMD		V1_CMDPOS_STARTOFCMD
#define V1_CMDPOS_ASSOC_GUID		V1_CMDPOS_ASSOC_SUBCMD + 1

#define V1_CMDPOS_ASSOCREQ_HW_VER	V1_CMDPOS_ASSOC_GUID + 8
#define V1_CMDPOS_ASSOCREQ_FW_VER	V1_CMDPOS_ASSOCREQ_HW_VER + 4
#define V1_CMDPOS_ASSOCREQ_RP_VER	V1_CMDPOS_ASSOCREQ_FW_VER + 4
#define V1_CMDPOS_ASSOCREQ_SYSSTAT 	V1_CMDPOS_ASSOCREQ_RP_VER + 1

#define V1_CMDPOS_ASSOCRESP_ADDR	V1_CMDPOS_ASSOC_GUID + 8
#define V1_CMDPOS_ASSOCRESP_NET		V1_CMDPOS_ASSOCRESP_ADDR + 2
#define V1_CMDPOS_ASSOCRESP_SLEEP	V1_CMDPOS_ASSOCRESP_NET + 1
#define V1_CMDPOS_ASSOCRESP_SCANNER V1_CMDPOS_ASSOCRESP_SLEEP + 2

#define V1_CMDPOS_ASSOCACK_STATE	V1_CMDPOS_ASSOC_GUID + 8
#define V1_CMDPOS_ASSOCACK_TIME		V1_CMDPOS_ASSOCACK_STATE + 1

#define V1_CMDPOS_ASSOCCHK_BATT		V1_CMDPOS_ASSOC_GUID + 8
#define V1_CMDPOS_ASSOCCHK_LRC		V1_CMDPOS_ASSOCCHK_BATT + 1
#define V1_CMDPOS_ASSOCCHK_RCM0		V1_CMDPOS_ASSOCCHK_LRC + 1
#define V1_CMDPOS_ASSOCCHK_RCM1		V1_CMDPOS_ASSOCCHK_RCM0 + 1
#define V1_CMDPOS_ASSOCCHK_PC		V1_CMDPOS_ASSOCCHK_RCM1 + 1

#endif /* APPLICATION_CONFIGURE_GATEWAYCOMMONTYPES_H_ */

